const columns = ["IDEA", "ASSESSED", "PRIORITIZED", "IN_PROGRESS", "VERIFYING", "COMPLETED"];
const columnLabels = { IDEA:"Ideias", ASSESSED:"Entendemos o problema", PRIORITIZED:"Escolhidas para fazer", IN_PROGRESS:"Em construção", VERIFYING:"Em verificação", COMPLETED:"Concluídas" };
const observed = ["PostgreSQL criado", "DbConn implementado", "ParticipationService implementado", "endpoints HTTP preliminares"];
const fallback = { plan_id:"PDE-SISTER-1.0", revision:"PLAN-REV-INITIAL", goal:{goal_id:"GOAL-MVP01",title:"Participação governada e reflexiva"}, actions:[{action_id:"PDE-MVP01-01",title:"Persistir candidatura e contrato de participação",state:"IDEA",gap_id:"GAP-MVP01-PARTICIPATION-PERSISTENCE",acceptance_criteria:["Contrato registrável e reconstruível."]}] };
const $ = s => document.querySelector(s); const esc = v => { const d=document.createElement("div"); d.textContent=v; return d.innerHTML; };
function render(plan) {
  $("#objective").textContent = `${plan.goal.title} · ${plan.goal.objective || "fechar o próximo ciclo com segurança"}`; $("#revision").textContent=plan.revision === "PLAN-REV-INITIAL" ? "Plano inicial" : plan.revision;
  const current=plan.actions.find(a=>a.state!=="COMPLETED")||plan.actions[0]; $("#current-action").textContent=current.title;
  $("#next-step").textContent=current.state === "IDEA" ? "Avaliar a proposta e decidir" : "Continuar a implementação"; $("#blockers").textContent=current.state === "IDEA" ? "aguarda decisão humana" : "nenhum registrado";
  const board=$("#board"); board.innerHTML=""; columns.forEach(column=>{ const el=document.createElement("div"); el.className="board-column"; el.innerHTML=`<h3>${columnLabels[column]}</h3><small>${column}</small>`; (plan.actions||[]).filter(a=>a.state===column).forEach(action=>{ const card=document.createElement("article"); card.className=`card ${action.action_id===current.action_id?"current":""}`; card.innerHTML=`<strong>${esc(action.title)}</strong><span>${esc(action.action_id)}</span>`; card.onclick=()=>showDetails(plan,action); el.append(card); }); board.append(el); });
}
function showDetails(plan, action) { const d=$("#details"); d.hidden=false; d.innerHTML=`<h3>${esc(action.title)}</h3><p class="detail-id">${esc(action.action_id)} · estado reconhecido: ${esc(action.state)}</p><div class="details-grid"><div class="detail-block"><strong>Por que isso importa</strong><p>Reduzir a distância entre uma candidatura de participação e um registro que possa ser consultado com segurança.</p></div><div class="detail-block"><strong>O que já conseguimos fazer</strong><p>${observed.map(esc).join(" · ")}</p></div><div class="detail-block"><strong>O que ainda falta</strong><p>${action.state === "IDEA" ? "Reconhecer a implementação por avaliação e decisão humana no plano." : "Concluir a verificação da entrega."}</p></div><div class="detail-block"><strong>Próximo passo</strong><p>${action.state === "IDEA" ? "Avaliar a ação e registrar a decisão adequada." : "Continuar conforme a autorização vigente."}</p></div><div class="detail-block"><strong>Como saberemos que terminou</strong><p>${(action.acceptance_criteria||[]).map(esc).join("<br>")}</p></div><div class="detail-block"><strong>Identificação técnica</strong><p>${esc(action.goal_id)} · ${esc(action.gap_id)}</p></div></div>`; d.scrollIntoView({behavior:"smooth",block:"start"}); }
fetch("/api/v1/engineering/plan").then(r=>r.ok?r.json():Promise.reject()).then(render).catch(()=>render(fallback));
