const columns = ["IDEA", "ASSESSED", "PRIORITIZED", "IN_PROGRESS", "VERIFYING", "COMPLETED"];
const observed = ["PostgreSQL criado", "DbConn implementado", "ParticipationService implementado", "endpoints HTTP preliminares"];
const fallback = { plan_id:"PDE-SISTER-1.0", revision:"PLAN-REV-INITIAL", goal:{goal_id:"GOAL-MVP01",title:"Participação governada e reflexiva"}, actions:[{action_id:"PDE-MVP01-01",title:"Persistir candidatura e contrato de participação",state:"IDEA",gap_id:"GAP-MVP01-PARTICIPATION-PERSISTENCE",acceptance_criteria:["Contrato registrável e reconstruível."]}] };
const $ = s => document.querySelector(s); const esc = v => { const d=document.createElement("div"); d.textContent=v; return d.innerHTML; };
function render(plan) {
  $("#objective").textContent = `${plan.goal.goal_id} · ${plan.goal.title}`; $("#revision").textContent=plan.revision;
  const current=plan.actions.find(a=>a.state!=="COMPLETED")||plan.actions[0]; $("#current-action").textContent=current.action_id;
  $("#next-step").textContent=current.state === "IDEA" ? "Avaliar e decidir" : "Executar ação"; $("#blockers").textContent=current.state === "IDEA" ? "decisão humana" : "nenhum registrado";
  const board=$("#board"); board.innerHTML=""; columns.forEach(column=>{ const el=document.createElement("div"); el.className="board-column"; el.innerHTML=`<h3>${column}</h3>`; (plan.actions||[]).filter(a=>a.state===column).forEach(action=>{ const card=document.createElement("article"); card.className=`card ${action.action_id===current.action_id?"current":""}`; card.innerHTML=`<strong>${esc(action.action_id)}</strong><span>${esc(action.title)}</span>`; card.onclick=()=>showDetails(plan,action); el.append(card); }); board.append(el); });
}
function showDetails(plan, action) { const d=$("#details"); d.hidden=false; d.innerHTML=`<h3>${esc(action.action_id)} · ${esc(action.title)}</h3><div class="details-grid"><div class="detail-block"><strong>Estado governado</strong><p>${esc(action.state)}</p></div><div class="detail-block"><strong>Implementação observada</strong><p>${observed.map(esc).join(" · ")}</p></div><div class="detail-block"><strong>Objetivo</strong><p>${esc(action.goal_id)}</p></div><div class="detail-block"><strong>Próxima transição</strong><p>${action.state === "IDEA" ? "IDEA → ASSESSED (avaliação persistida)" : "conforme decisão vigente"}</p></div><div class="detail-block"><strong>Critérios</strong><p>${(action.acceptance_criteria||[]).map(esc).join("<br>")}</p></div><div class="detail-block"><strong>Divergência</strong><p>O plano ainda registra IDEA enquanto a implementação já possui uma fatia experimental comprovada.</p></div></div>`; d.scrollIntoView({behavior:"smooth",block:"start"}); }
fetch("/api/v1/engineering/plan").then(r=>r.ok?r.json():Promise.reject()).then(render).catch(()=>render(fallback));
